import type { Lang } from './domain';

export const localeCode = (lang: Lang) => lang === 'uz' ? 'uz-UZ' : lang === 'en' ? 'en-US' : 'ru-RU';
export const formatDate = (value: string | Date, lang: Lang) => new Date(value).toLocaleDateString(localeCode(lang));
export const formatDateTime = (value: string | Date, lang: Lang) => new Date(value).toLocaleString(localeCode(lang));

export const uiCopy = {
  ru: {
    choose: 'Выбери роль', subtitle: 'Каждый участник видит только нужные ему данные', home: 'Сводка', objects: 'Объекты', tasks: 'Задачи', quality: 'Контроль', cameras: 'Камеры', feed: 'Лента', supply: 'Учет', profile: 'Профиль', portfolio: 'Портфель компании', openTasks: 'Открытые задачи', defects: 'Дефекты', delayed: 'Риск срока', progress: 'Готовность', plan: 'План', deadline: 'Срок', forecast: 'Прогноз', changeRole: 'Сменить роль', language: 'Язык интерфейса', online: 'онлайн', offline: 'офлайн', allObjects: 'Все объекты', myTasks: 'Задачи и план работ', role: 'Роль', stage02: 'StroyControl 1.0',
    searchObject: 'Поиск по объекту или адресу', nothingFound: 'Ничего не найдено', daysShort: 'дн', object: 'Объект', stage: 'Этап', responsible: 'Ответственный', priority: 'Приоритет', status: 'Статус', checklist: 'Чек-лист ответственного', inspectorChecklist: 'Чек-лист технадзора', verifyWork: 'Работа соответствует заданию', verifyPhotos: 'Фото и ракурсы проверены', verifyLocation: 'Геолокация подтверждена', inspectorChecklistRequired: 'Отметь все пункты проверки перед приемкой.', high: 'Высокий', medium: 'Средний', low: 'Низкий', assignInspector: 'Назначить технадзор', assignedNow: 'Сейчас назначен', reviewerMissing: 'Проверяющий еще не назначен', noInspectors: 'На объекте нет пользователей с ролью технадзора.', closeWithPhoto: 'Добавить фото', submitWithPhotos: 'Отправить фото и GPS', attachedPhotos: 'Прикрепленные фото', removePhoto: 'Удалить', photoLimit: 'Можно прикрепить до 10 фото.', photoRequired: 'Добавь хотя бы одно фото.', inspectorDecision: 'Решение технадзора', reviewComment: 'Комментарий, обязателен при отклонении', accept: 'Принять', reject: 'Отклонить', reviewCommentRequired: 'Нужен комментарий', rejectionReason: 'Укажи причину отклонения.', reviewResult: 'Комментарий проверки', syncQueue: 'В очереди синхронизации', permissionsNeeded: 'Нужны разрешения', permissionsBody: 'Разреши камеру и геолокацию для закрытия задачи.', sentForReview: 'Отправлено на проверку', savedOffline: 'Фото, GPS и время сохранены в офлайн-очереди.',
  },
  uz: {
    choose: 'Rolni tanlang', subtitle: "Har bir ishtirokchi faqat kerakli ma'lumotlarni ko'radi", home: 'Umumiy', objects: 'Obyektlar', tasks: 'Vazifalar', quality: 'Nazorat', cameras: 'Kameralar', feed: 'Lenta', supply: 'Hisob', profile: 'Profil', portfolio: 'Kompaniya portfeli', openTasks: 'Ochiq vazifalar', defects: 'Nuqsonlar', delayed: 'Muddat xavfi', progress: 'Tayyorlik', plan: 'Reja', deadline: 'Muddat', forecast: 'Prognoz', changeRole: 'Rolni almashtirish', language: 'Interfeys tili', online: 'onlayn', offline: 'oflayn', allObjects: 'Barcha obyektlar', myTasks: 'Vazifalar va ish rejasi', role: 'Rol', stage02: 'StroyControl 1.0',
    searchObject: "Obyekt yoki manzil bo'yicha qidirish", nothingFound: 'Hech narsa topilmadi', daysShort: 'kun', object: 'Obyekt', stage: 'Bosqich', responsible: "Mas'ul", priority: 'Ustuvorlik', status: 'Holat', checklist: "Mas'ul shaxs ro'yxati", inspectorChecklist: "Texnik nazorat ro'yxati", verifyWork: 'Ish topshiriqqa mos', verifyPhotos: 'Foto va rakurslar tekshirildi', verifyLocation: 'Geolokatsiya tasdiqlandi', inspectorChecklistRequired: "Qabul qilishdan oldin barcha tekshiruvlarni belgilang.", high: 'Yuqori', medium: "O'rta", low: 'Past', assignInspector: 'Texnik nazoratchini tayinlash', assignedNow: 'Hozir tayinlangan', reviewerMissing: 'Tekshiruvchi hali tayinlanmagan', noInspectors: "Obyektda texnik nazoratchi roli bilan foydalanuvchi yo'q.", closeWithPhoto: "Foto qo'shish", submitWithPhotos: 'Foto va GPS yuborish', attachedPhotos: 'Biriktirilgan rasmlar', removePhoto: "O'chirish", photoLimit: "10 tagacha foto biriktirish mumkin.", photoRequired: "Kamida bitta foto qo'shing.", inspectorDecision: 'Texnik nazorat qarori', reviewComment: 'Izoh, rad etishda majburiy', accept: 'Qabul qilish', reject: 'Rad etish', reviewCommentRequired: 'Izoh kerak', rejectionReason: 'Rad etish sababini kiriting.', reviewResult: 'Tekshiruv izohi', syncQueue: 'Sinxronlash navbatida', permissionsNeeded: 'Ruxsatlar kerak', permissionsBody: 'Vazifani yopish uchun kamera va geolokatsiyaga ruxsat bering.', sentForReview: 'Tekshiruvga yuborildi', savedOffline: 'Foto, GPS va vaqt oflayn navbatga saqlandi.',
  },
  en: {
    choose: 'Choose a role', subtitle: 'Each participant sees only the information they need', home: 'Overview', objects: 'Sites', tasks: 'Tasks', quality: 'Quality', cameras: 'Cameras', feed: 'Feed', supply: 'Inventory', profile: 'Profile', portfolio: 'Company portfolio', openTasks: 'Open tasks', defects: 'Defects', delayed: 'Deadline risk', progress: 'Progress', plan: 'Plan', deadline: 'Deadline', forecast: 'Forecast', changeRole: 'Change role', language: 'Interface language', online: 'online', offline: 'offline', allObjects: 'All sites', myTasks: 'Tasks and work plan', role: 'Role', stage02: 'StroyControl 1.0',
    searchObject: 'Search by site or address', nothingFound: 'Nothing found', daysShort: 'days', object: 'Site', stage: 'Stage', responsible: 'Responsible', priority: 'Priority', status: 'Status', checklist: 'Responsible checklist', inspectorChecklist: 'Inspector checklist', verifyWork: 'Work matches the task', verifyPhotos: 'Photos and angles checked', verifyLocation: 'Location confirmed', inspectorChecklistRequired: 'Complete every inspection item before accepting.', high: 'High', medium: 'Medium', low: 'Low', assignInspector: 'Assign inspector', assignedNow: 'Currently assigned', reviewerMissing: 'No reviewer assigned yet', noInspectors: 'There are no technical inspectors on this site.', closeWithPhoto: 'Add photo', submitWithPhotos: 'Send photos and GPS', attachedPhotos: 'Attached photos', removePhoto: 'Remove', photoLimit: 'You can attach up to 10 photos.', photoRequired: 'Add at least one photo.', inspectorDecision: 'Inspector decision', reviewComment: 'Comment, required when rejecting', accept: 'Accept', reject: 'Reject', reviewCommentRequired: 'Comment required', rejectionReason: 'Enter the rejection reason.', reviewResult: 'Review comment', syncQueue: 'In sync queue', permissionsNeeded: 'Permissions required', permissionsBody: 'Allow camera and location access to close the task.', sentForReview: 'Sent for review', savedOffline: 'Photo, GPS and time saved to the offline queue.',
  },
} as const;

export type UiCopy = typeof uiCopy.ru | typeof uiCopy.uz | typeof uiCopy.en;
